"""Rung 2 -- DPO/KTO on same-state preference pairs.

The within-state contrast cancels `V(s_t)` EXACTLY, whereas terminal-reward policy gradient
must estimate it across tasks whose difficulty variance dwarfs the treatment effect. That one
sentence is why this rung costs ~25 GPU-h and rung 3 costs $2,400. See `train.py` for the
argument written out.
"""

from .train import (
    DEFAULT_LOSS_TYPE,
    LABEL_SOURCES,
    LOSS_TYPES,
    POLICY_ADAPTER,
    REFERENCE_ADAPTER,
    REFERENCES,
    SAMPLED_PAIR_KINDS,
    AmbiguousReference,
    DPOConfig,
    EncodedPair,
    HeldOutDataset,
    NoPairs,
    NotSameState,
    TooFewPairsToSubsample,
    TooFewStopPairs,
    UnknownReferenceHook,
    UnsupportedObjective,
    adapter_lora_spec,
    assert_length_guard,
    assert_same_state,
    assert_trainable_split,
    base_reference_hook,
    dpo_argument_kwargs,
    encode_pairs,
    estimate_gpu_hours,
    installed_loss_types,
    load_pairs,
    pair_kind_of,
    pairs_report,
    preflight,
    reference_hook,
    rows_for,
    subsample_rows,
    train,
    verify_base_reference,
    verify_frozen_reference,
)

__all__ = [
    "DEFAULT_LOSS_TYPE",
    "LABEL_SOURCES",
    "LOSS_TYPES",
    "POLICY_ADAPTER",
    "REFERENCES",
    "REFERENCE_ADAPTER",
    "SAMPLED_PAIR_KINDS",
    "AmbiguousReference",
    "DPOConfig",
    "EncodedPair",
    "HeldOutDataset",
    "NoPairs",
    "NotSameState",
    "TooFewPairsToSubsample",
    "TooFewStopPairs",
    "UnknownReferenceHook",
    "UnsupportedObjective",
    "adapter_lora_spec",
    "assert_length_guard",
    "assert_same_state",
    "assert_trainable_split",
    "base_reference_hook",
    "dpo_argument_kwargs",
    "encode_pairs",
    "estimate_gpu_hours",
    "installed_loss_types",
    "load_pairs",
    "pair_kind_of",
    "pairs_report",
    "preflight",
    "reference_hook",
    "rows_for",
    "subsample_rows",
    "train",
    "verify_base_reference",
    "verify_frozen_reference",
]
